services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Oliverde8\PhpEtlBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../..//Entity/'
      - '../../Tests/'
      - '../../Etl/Operation'

  Oliverde8\PhpEtlBundle\Services\ChainWorkDirManager:
    class: Oliverde8\PhpEtlBundle\Services\ChainWorkDirManager
    arguments:
      $tmpBaseDir: "%oliverde8.php.etl.base_dir%"

  # Import etl operation separately.s
  Oliverde8\PhpEtlBundle\Etl\OperationFactory\:
    resource: '../../Etl/OperationFactory/'
    tags: [ 'etl.operation-factory' ]

  Oliverde8\Component\PhpEtl\ChainBuilder:
    class: Oliverde8\Component\PhpEtl\ChainBuilder

  Oliverde8\Component\RuleEngine\RuleApplier:
    class: Oliverde8\Component\RuleEngine\RuleApplier
    arguments:
      $rules: [ ]
      $validate: true

  Oliverde8\PhpEtlBundle\Etl\OperationFactory\Cleanup\FindOldExecutionsFactory:
    arguments:
      $minKeep: '%oliverde8.php.etl.min_keep%'
    tags: [ 'etl.operation-factory' ]
